#include "framework.h"

void L1_1(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    POINT poly[4];
    poly[0].x = 150;
    poly[0].y = 350;
    poly[1].x = 275;
    poly[1].y = 250;
    poly[2].x = 400;
    poly[2].y = 350;
    SelectObject(hdc, hBrush_wood_lite);
    Polygon(hdc, poly, 3);
    MoveToEx(hdc, 150, 350, NULL);
    LineTo(hdc, 275, 250);
    LineTo(hdc, 400, 350);
    // Дом
    RECT rect_house = { 150, 350, 400, 525 };
    FillRect(hdc, &rect_house, hBrush_wood);
    LineTo(hdc, 400, 525);
    LineTo(hdc, 150, 525);
    LineTo(hdc, 150, 350);
    LineTo(hdc, 400, 350);
    // Окно
    RECT rect_window = { 225, 400, 325, 475 };
    FillRect(hdc, &rect_window, hBrush_cloud);
    MoveToEx(hdc, 225, 400, NULL);
    LineTo(hdc, 225, 475);
    LineTo(hdc, 325, 475);
    LineTo(hdc, 325, 400);
    LineTo(hdc, 225, 400);
    // Рама
    MoveToEx(hdc, 275, 400, NULL);
    LineTo(hdc, 275, 475);
    MoveToEx(hdc, 275, 425, NULL);
    LineTo(hdc, 325, 425);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_2(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    SelectObject(hdc, hBrush_wood_lite);
    MoveToEx(hdc, 500, 400, NULL);
    LineTo(hdc, 525, 375);
    LineTo(hdc, 550, 400);
    LineTo(hdc, 500, 400);
    MoveToEx(hdc, 475, 450, NULL);
    LineTo(hdc, 525, 400);
    LineTo(hdc, 575, 450);
    LineTo(hdc, 475, 450);
    MoveToEx(hdc, 450, 525, NULL);
    LineTo(hdc, 525, 450);
    LineTo(hdc, 600, 525);
    LineTo(hdc, 450, 525);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_3(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Деревце

    //Ствол
    SelectObject(hdc, hPen_stvol);
    MoveToEx(hdc, 700, 525, NULL);
    LineTo(hdc, 700, 350);
    //Крона
    SelectObject(hdc, hPen_crona);
    SelectObject(hdc, hBrush_crona);
    Ellipse(hdc, 650, 250, 750, 450);
    SelectObject(hdc, hPen_crona_dark);
    SelectObject(hdc, hBrush_crona_dark);
    Ellipse(hdc, 672, 380, 690, 400);
    Ellipse(hdc, 722, 330, 740, 350);
    Ellipse(hdc, 692, 280, 710, 300);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_4(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Солнышко
    SelectObject(hdc, hPen_sun);
    SelectObject(hdc, hBrush_sun);
    Ellipse(hdc, 50, 50, 150, 150);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_5(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Облако
    SelectObject(hdc, hPen_cloud);
    SelectObject(hdc, hBrush_cloud);
    Ellipse(hdc, 300, 50, 500, 150);
    Ellipse(hdc, 350, 100, 550, 200);
    Ellipse(hdc, 450, 100, 650, 194);
    Ellipse(hdc, 420, 30, 660, 130);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_6(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Лучи
    SelectObject(hdc, hPen_sun);
    MoveToEx(hdc, 60, 150, NULL);
    LineTo(hdc, 40, 200);
    MoveToEx(hdc, 100, 160, NULL);
    LineTo(hdc, 100, 220);
    MoveToEx(hdc, 145, 150, NULL);
    LineTo(hdc, 175, 200);
    MoveToEx(hdc, 160, 125, NULL);
    LineTo(hdc, 200, 160);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_7(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Машина
    //Кузов
    POINT poly1[11];
    poly1[0].x = 100;
    poly1[0].y = 800;
    poly1[1].x = 500;
    poly1[1].y = 800;
    poly1[2].x = 500;
    poly1[2].y = 740;
    poly1[3].x = 490;
    poly1[3].y = 740;
    poly1[4].x = 490;
    poly1[4].y = 650;
    poly1[5].x = 240;
    poly1[5].y = 650;
    poly1[6].x = 220;
    poly1[6].y = 720;
    poly1[7].x = 110;
    poly1[7].y = 720;
    poly1[8].x = 110;
    poly1[8].y = 740;
    poly1[9].x = 100;
    poly1[9].y = 740;
    poly1[10].x = 100;
    poly1[10].y = 800;
    SelectObject(hdc, hPen_line);
    SelectObject(hdc, hBrush_red_car);
    Polygon(hdc, poly1, 11);

    //Стекла
    POINT poly2[5];
    poly2[0].x = 240;
    poly2[0].y = 720;
    poly2[1].x = 255;
    poly2[1].y = 660;
    poly2[2].x = 470;
    poly2[2].y = 660;
    poly2[3].x = 470;
    poly2[3].y = 720;
    poly2[4].x = 240;
    poly2[4].y = 720;
    SelectObject(hdc, hPen_line);
    SelectObject(hdc, hBrush_cloud);
    Polygon(hdc, poly2, 5);

    MoveToEx(hdc, 300, 660, NULL);
    LineTo(hdc, 300, 720);
    MoveToEx(hdc, 400, 660, NULL);
    LineTo(hdc, 400, 720);
    //Колеса
    SelectObject(hdc, hBrush_black_car);
    Ellipse(hdc, 130, 740, 230, 840);
    Ellipse(hdc, 370, 740, 470, 840);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}

void L1_8(HDC hdc) {
    HPEN hPen_stvol;
    HPEN hPen_crona;
    HPEN hPen_crona_dark;
    HPEN hPen_sun;
    HPEN hPen_cloud;
    HPEN hPen_line;
    HPEN hPen_wood;
    HPEN hPen_white;
    HBRUSH hBrush_line;
    HBRUSH hBrush_crona;
    HBRUSH hBrush_crona_dark;
    HBRUSH hBrush_sun;
    HBRUSH hBrush_cloud;
    HBRUSH hBrush_wood;
    HBRUSH hBrush_wood_lite;
    HBRUSH hBrush_red_car;
    HBRUSH hBrush_black_car;
    HBRUSH hBrush_white;
    hPen_line = CreatePen(PS_SOLID, 1, RGB(0, 0, 0));
    hPen_stvol = CreatePen(PS_SOLID, 20, RGB(119, 38, 19));
    hPen_crona = CreatePen(PS_SOLID, 20, RGB(27, 111, 12));
    hPen_crona_dark = CreatePen(PS_SOLID, 20, RGB(12, 45, 1));
    hPen_sun = CreatePen(PS_SOLID, 5, RGB(214, 228, 0));
    hPen_cloud = CreatePen(PS_SOLID, 5, RGB(145, 173, 255));
    hPen_wood = CreatePen(PS_SOLID, 1, RGB(132, 77, 44));
    hPen_white = CreatePen(PS_SOLID, 1, RGB(255, 255, 255));
    hBrush_crona = CreateSolidBrush(RGB(27, 111, 12));
    hBrush_crona_dark = CreateSolidBrush(RGB(12, 45, 1));
    hBrush_sun = CreateHatchBrush(HS_CROSS, RGB(214, 228, 0));
    hBrush_cloud = CreateSolidBrush(RGB(145, 173, 255));
    hBrush_wood = CreateSolidBrush(RGB(132, 77, 44));
    hBrush_wood_lite = CreateSolidBrush(RGB(173, 107, 55));
    hBrush_line = CreateSolidBrush(RGB(255, 255, 255));
    hBrush_red_car = CreateSolidBrush(RGB(255, 0, 0));
    hBrush_black_car = CreateSolidBrush(RGB(0, 0, 0));
    hBrush_white = CreateSolidBrush(RGB(255, 255, 255));

    // Infiniti
    SelectObject(hdc, hBrush_black_car);
    SelectObject(hdc, hPen_line);
    Ellipse(hdc, 1500, 500, 1700, 600);
    SelectObject(hdc, hBrush_white);
    SelectObject(hdc, hPen_white);
    Ellipse(hdc, 1525, 515, 1675, 575);
    POINT infi1[4];
    infi1[0].x = 1600;
    infi1[0].y = 525;
    infi1[1].x = 1655;
    infi1[1].y = 585;
    infi1[2].x = 1545;
    infi1[2].y = 585;
    SelectObject(hdc, hPen_line);
    SelectObject(hdc, hBrush_black_car);
    Polygon(hdc, infi1, 3);
    POINT infi[4];
    infi[0].x = 1600;
    infi[0].y = 535;
    infi[1].x = 1635;
    infi[1].y = 615;
    infi[2].x = 1565;
    infi[2].y = 615;
    SelectObject(hdc, hPen_white);
    SelectObject(hdc, hBrush_white);
    Polygon(hdc, infi, 3);

    DeleteObject(hPen_stvol);
    DeleteObject(hPen_crona);
    DeleteObject(hPen_crona_dark);
    DeleteObject(hPen_sun);
    DeleteObject(hPen_cloud);
    DeleteObject(hPen_line);
    DeleteObject(hPen_wood);
    DeleteObject(hPen_white);
    DeleteObject(hBrush_line);
    DeleteObject(hBrush_crona);
    DeleteObject(hBrush_crona_dark);
    DeleteObject(hBrush_sun);
    DeleteObject(hBrush_cloud);
    DeleteObject(hBrush_wood);
    DeleteObject(hBrush_wood_lite);
    DeleteObject(hBrush_red_car);
    DeleteObject(hBrush_black_car);
    DeleteObject(hBrush_white);
}